import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Ingredients from "../components/Ingredients";
import Recipes from "../components/Recipes";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [recipes, setRecipes] = useState([]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Recipe Generator!</h1>

        <p className={styles.description}>
          Get started by adding ingredients below.
        </p>

        <Ingredients
          onUpdate={async (ingredients) => {
            const queryString = ingredients
              .map((i) => i.value.trim())
              .join(",");
            const res = await fetch(`/api/recipes?q=${queryString}`);
            const { data } = await res.json();
            setRecipes(data);
          }}
        />
      </main>

      <section>
        <Recipes recipes={recipes} />
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
