import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import IngredientsInput from "../components/IngredientsInput";
import IngredientsList from "../components/IngredientsList";
import styles from "../styles/Home.module.css";
import { v4 } from "uuid";

export default function Home() {
  const [ingredients, setIngredients] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Recipe Generator!</h1>

        <p className={styles.description}>
          Get started by adding ingredients below.
        </p>

        <IngredientsInput
          onSubmit={(ingredient) => {
            setIngredients([...ingredients, { id: v4(), value: ingredient }]);
          }}
        />

        <div className={styles.grid}>
          <IngredientsList
            onRemove={(ingredientId) => {
              setIngredients(ingredients.filter((i) => i.id !== ingredientId));
            }}
            ingredients={ingredients}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
